export const GET_ALL_PLANETS = 'GET_ALL_PLANETS';
export const GET_PLANET_INFO = 'GET_PLANET_INFO';
export const GET_PLANET_FILMS = 'GET_PLANET_FILMS';
export const GET_PLANET_RESIDENTS = 'GET_PLANET_RESIDENTS';
export const GET_NEXT_PAGE = 'GET_NEXT_PAGE';
export const GET_PREV_PAGE = 'GET_PREV_PAGE';
